name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: Windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up xmake
      uses: xmake-io/github-action-setup-xmake@v1

    - name: Configure xmake
      run: xmake f -p windows -a x64 -m debug

    - name: Test
      run: xmake test

    - name: Build
      run: xmake
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
        name: cheat
        path: build

    - name: SonarQube Scan for C and C++
      uses: SonarSource/sonarqube-github-c-cpp@v2.1.0
      with:
        cache-binaries: true
              